-- Chapter 1 SQL layer for SGVP 2023 donor analysis.
-- Import data/processed/sgvp_2023_chapter1_analytical.csv as table sgvp_chapter1.
-- Weighted estimates use WGHT_PER. Donation amount/frequency metrics are among donors only.

CREATE VIEW IF NOT EXISTS vw_chapter1_overall AS
SELECT
  COUNT(*) AS sample_respondents,
  SUM(WGHT_PER) AS weighted_population,
  SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) AS sample_donors,
  SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) AS weighted_donors,
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) / COUNT(*) AS sample_donor_rate_pct,
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) / SUM(WGHT_PER) AS weighted_donor_rate_pct,
  AVG(CASE WHEN FG1FGIV = 1 THEN donation_amount END) AS sample_mean_donation_among_donors,
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_amount * WGHT_PER ELSE 0 END)
    / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0) AS weighted_mean_donation_among_donors,
  AVG(CASE WHEN FG1FGIV = 1 THEN donation_count END) AS sample_mean_frequency_among_donors,
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_count * WGHT_PER ELSE 0 END)
    / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0) AS weighted_mean_frequency_among_donors
FROM sgvp_chapter1;

CREATE VIEW IF NOT EXISTS vw_chapter1_age AS
SELECT
  'AGEGR10' AS segment_variable,
  age_group AS segment,
  COUNT(*) AS sample_n,
  SUM(WGHT_PER) AS weighted_population,
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) / COUNT(*) AS sample_donor_rate_pct,
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) / SUM(WGHT_PER) AS weighted_donor_rate_pct,
  SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) AS weighted_donors,
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_amount * WGHT_PER ELSE 0 END)
    / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0) AS weighted_mean_donation,
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_count * WGHT_PER ELSE 0 END)
    / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0) AS weighted_mean_frequency
FROM sgvp_chapter1
GROUP BY age_group;

CREATE VIEW IF NOT EXISTS vw_chapter1_segments AS
SELECT * FROM vw_chapter1_age
UNION ALL
SELECT 'GENDER2', gender, COUNT(*), SUM(WGHT_PER),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) / COUNT(*),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) / SUM(WGHT_PER),
  SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_amount * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_count * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0)
FROM sgvp_chapter1 GROUP BY gender
UNION ALL
SELECT 'PRV', province, COUNT(*), SUM(WGHT_PER),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) / COUNT(*),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) / SUM(WGHT_PER),
  SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_amount * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_count * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0)
FROM sgvp_chapter1 GROUP BY province
UNION ALL
SELECT 'INCG2', personal_income, COUNT(*), SUM(WGHT_PER),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) / COUNT(*),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) / SUM(WGHT_PER),
  SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_amount * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_count * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0)
FROM sgvp_chapter1 GROUP BY personal_income
UNION ALL
SELECT 'FAMINCG2', family_income, COUNT(*), SUM(WGHT_PER),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) / COUNT(*),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) / SUM(WGHT_PER),
  SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_amount * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_count * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0)
FROM sgvp_chapter1 GROUP BY family_income
UNION ALL
SELECT 'ED4CAT', education, COUNT(*), SUM(WGHT_PER),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN 1 ELSE 0 END) / COUNT(*),
  100.0 * SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END) / SUM(WGHT_PER),
  SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_amount * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0),
  SUM(CASE WHEN FG1FGIV = 1 THEN donation_count * WGHT_PER ELSE 0 END) / NULLIF(SUM(CASE WHEN FG1FGIV = 1 THEN WGHT_PER ELSE 0 END), 0)
FROM sgvp_chapter1 GROUP BY education;
