table tbl_page5_barrier_summary
	lineageTag: 4911e56f-ca78-4331-aad2-c98e948698e0

	column chapter
		dataType: string
		lineageTag: fcaeca55-beaf-4673-acde-83af93287cf5
		summarizeBy: none
		sourceColumn: chapter

		annotation SummarizationSetBy = Automatic

	column comparison_group
		dataType: string
		lineageTag: 46fa950f-174b-4323-aff2-07bb0d0ff43d
		summarizeBy: none
		sourceColumn: comparison_group

		annotation SummarizationSetBy = Automatic

	column barrier_variable
		dataType: string
		lineageTag: 05f1c17a-ea4d-49ac-8722-507dd15324c7
		summarizeBy: none
		sourceColumn: barrier_variable

		annotation SummarizationSetBy = Automatic

	column barrier_label
		dataType: string
		lineageTag: 330d1d34-8850-48e3-9085-55dadb3b3e06
		summarizeBy: none
		sourceColumn: barrier_label

		annotation SummarizationSetBy = Automatic

	column barrier_category
		dataType: string
		lineageTag: c32766b3-c2e7-4f3b-aa0a-bee4be5327b1
		summarizeBy: none
		sourceColumn: barrier_category

		annotation SummarizationSetBy = Automatic

	column applicability
		dataType: string
		lineageTag: 09532411-6321-4948-9431-cbe64e2c50ae
		summarizeBy: none
		sourceColumn: applicability

		annotation SummarizationSetBy = Automatic

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 179dae56-9adb-4dc2-882a-2a4058227a17
		summarizeBy: none
		sourceColumn: sort_order

		annotation SummarizationSetBy = Automatic

	column sample_group_n
		dataType: int64
		formatString: 0
		lineageTag: 9cea692c-1ba0-4c88-8427-05502a24169f
		summarizeBy: sum
		sourceColumn: sample_group_n

		annotation SummarizationSetBy = Automatic

	column weighted_group_population
		dataType: int64
		formatString: 0
		lineageTag: 4d9b45bd-0560-4ce2-a085-5f3d00830712
		summarizeBy: sum
		sourceColumn: weighted_group_population

		annotation SummarizationSetBy = Automatic

	column valid_denominator_weighted
		dataType: int64
		formatString: 0
		lineageTag: b84dfef4-b917-463d-9589-c42ffb07970c
		summarizeBy: sum
		sourceColumn: valid_denominator_weighted

		annotation SummarizationSetBy = Automatic

	column sample_yes_n
		dataType: int64
		formatString: 0
		lineageTag: e6475a89-57cb-4d5a-bb00-c8097f6792ce
		summarizeBy: sum
		sourceColumn: sample_yes_n

		annotation SummarizationSetBy = Automatic

	column weighted_yes
		dataType: int64
		formatString: 0
		lineageTag: d379d285-f1a3-4af8-b2cf-887e5dff7638
		summarizeBy: sum
		sourceColumn: weighted_yes

		annotation SummarizationSetBy = Automatic

	column weighted_yes_pct
		dataType: double
		lineageTag: e7f43444-5f5b-41ab-ae7c-646f80d8d41b
		summarizeBy: sum
		sourceColumn: weighted_yes_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column health_vs_nonhealth_gap_pct_points
		dataType: double
		lineageTag: aa0e44a6-3912-4a78-82f7-e2cdfa58db0b
		summarizeBy: sum
		sourceColumn: health_vs_nonhealth_gap_pct_points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition tbl_page5_barrier_summary = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(PowerBIWorkbookPath), null, true),
				    tbl_page5_barrier_summary_Table = Source{[Item="tbl_page5_barrier_summary",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(tbl_page5_barrier_summary_Table,{{"chapter", type text}, {"comparison_group", type text}, {"barrier_variable", type text}, {"barrier_label", type text}, {"barrier_category", type text}, {"applicability", type text}, {"sort_order", Int64.Type}, {"sample_group_n", Int64.Type}, {"weighted_group_population", Int64.Type}, {"valid_denominator_weighted", Int64.Type}, {"sample_yes_n", Int64.Type}, {"weighted_yes", Int64.Type}, {"weighted_yes_pct", type number}, {"health_vs_nonhealth_gap_pct_points", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

