table tbl_MANIFEST
	lineageTag: b2772e22-3049-49b2-aa82-5278be4eddc5

	column original_csv_filename
		dataType: string
		lineageTag: b0a1f912-febf-4f83-96d9-5e36e342f8e4
		summarizeBy: none
		sourceColumn: original_csv_filename

		annotation SummarizationSetBy = Automatic

	column excel_worksheet_name
		dataType: string
		lineageTag: 8583ec11-9884-454f-a112-712b3977ec23
		summarizeBy: none
		sourceColumn: excel_worksheet_name

		annotation SummarizationSetBy = Automatic

	column excel_table_name
		dataType: string
		lineageTag: 630e5c2d-c58f-4810-9c04-a34f7370be03
		summarizeBy: none
		sourceColumn: excel_table_name

		annotation SummarizationSetBy = Automatic

	column dashboard_page
		dataType: string
		lineageTag: 249e9500-960b-4a23-815c-3916ef6dd0f2
		summarizeBy: none
		sourceColumn: dashboard_page

		annotation SummarizationSetBy = Automatic

	column analytical_purpose
		dataType: string
		lineageTag: f33715d7-ae42-48f5-a076-3ebad9f88b54
		summarizeBy: none
		sourceColumn: analytical_purpose

		annotation SummarizationSetBy = Automatic

	column row_count
		dataType: int64
		formatString: 0
		lineageTag: 0f49750b-f288-471f-a26f-5cf6b308c814
		summarizeBy: sum
		sourceColumn: row_count

		annotation SummarizationSetBy = Automatic

	column column_count
		dataType: int64
		formatString: 0
		lineageTag: 4b4501cf-2ef1-4569-93f4-3d8b1d511cbf
		summarizeBy: sum
		sourceColumn: column_count

		annotation SummarizationSetBy = Automatic

	partition tbl_MANIFEST = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(PowerBIWorkbookPath), null, true),
				    tbl_MANIFEST_Table = Source{[Item="tbl_MANIFEST",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(tbl_MANIFEST_Table,{{"original_csv_filename", type text}, {"excel_worksheet_name", type text}, {"excel_table_name", type text}, {"dashboard_page", type text}, {"analytical_purpose", type text}, {"row_count", Int64.Type}, {"column_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

